### ISSUE TITLE
Static environment based AWS credentials not working

### ISSUE THREAD

**Issue by ebini** [idealo/aws-signing-proxy#11]
Hi,

i set in the docker container (v1.1.0) the env variables:
AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_REGION
(and ASP_TARGET_URL )

but I get "No valid credentials provider given! Valid providers are: oidc, vault"         

I would have expected that this would work only with these Environment Variables.

Thanks

**Comment by theurichde** [comment]
Hi.

>  I would have expected that this would work only with these Environment Variables.

Well, no. The ASP is not designed to support plain request signing with static credentials.
It is designed to fetch short living credentials either via vault or openID connect.

If you want to have plain request signing with your static credentials, I would like to propose you writing your own signer for that. You can orient on the proxy package / the proxy.go, especially proxy.go:50 the _director_ function. You would have to adapt the credentials chain there.
