### ISSUE TITLE
Feature: Use Service Account (Annotation) in Kubernetes

### ISSUE THREAD

**Issue by ebini** [idealo/aws-signing-proxy#12]
Hi,

I need a proxy to Elastic Search (Opensearch) in a EKS.
I want to use this service within a pod (docker image) and a service account
(and the pod annotation to map to an IAM Role)

(See https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)

Not sure what this means for this tool or if it is possible. Perhaps it is connected to #1 

Thanks in advance.

**Comment by theurichde** [comment]
Will be fixed with #52
