### ISSUE TITLE
[feature] If connection to the OIDC provider is gone use a backoff-policy instead restart

### ISSUE THREAD

**Issue by SvenEhmann** [idealo/aws-signing-proxy#33]
**Is your feature request related to a problem? Please describe.**
If the proxy doesn't can connect to the OIDC provider, the proxy fails and restart. This behavior leads to a lot of unspecific crash-loop alarms.

**Describe the solution you'd like**
If the connection doesn't work the proxy should retry it with a backoff policy. The failed connection should be logged and provided as a metric that can be collected by Prometheus.
This behavior prevents restarting and offers the possibility to stabilize the connection in between. And for the OIDC provider is it a better behavior than a "DDOS" of requests after the connection goes lost. 

**Additional context**
It would be cool if the feature is implemented with a feature toggle, so the behavior is as before, and only if you like you could switch to the new behavior. And it would be great if the backoff interval could be configurable. Thanks. :-)

**Comment by theurichde** [comment]
will be fixed with #35

**Comment by theurichde** [comment]
Resolved with #35
